
# Set up conda environment
tasks:
  - name: Set up conda environment
    init: |
      # Download and install Miniconda
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
      bash /tmp/miniconda.sh -b -p "${HOME}/conda" && \
      rm /tmp/miniconda.sh

      # Add conda to PATH
      export PATH="${HOME}/conda/bin:${PATH}"

      # Initialize conda
      conda init bash

      # Create a new environment with the packages you need
      conda create -n myenv python=3.8 pandas scikit-learn

      # Activate the environment
      conda activate myenv