
# Set up conda environment
tasks:
  - name: Set up conda environment
    before: |
      # Download and install Miniconda
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
      bash /tmp/miniconda.sh -b -p "${HOME}/conda" && \
      rm /tmp/miniconda.sh

      # Add conda to PATH
      export PATH="${HOME}/conda/bin:${PATH}"

      # Initialize conda
      conda init bash

    init: |
      # Create a new environment with the packages you need
      conda env create -f environment.yaml --yes

      # Activate the environment
      conda activate mlflowenv
      pip install -r requirements.txt